import { Component, signal, effect, inject, OnInit, OnDestroy } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { Subscription } from 'rxjs';
import { ApiService } from '../../../core/services/api.service';
import { ChatbotWsService, ProactiveAlertPayload } from '../../../core/services/chatbot-ws.service';

export interface Source {
  name: string;
  score?: number;
  type?: string;
  url?: string;
}

export interface ThinkingStep {
  label: string;
  status: 'pending' | 'running' | 'done';
}

export interface Message {
  id: string;
  role: 'bot' | 'user';
  text: string;
  sources?: Source[];
  thinkingSteps?: ThinkingStep[];
  timestamp: Date;
  serverMessageId?: string;  // Backend UUID for feedback
  feedback?: 'up' | 'down' | 'none';
  isProactive?: boolean;     // True if generated by proactive alert system
  proactiveAlertId?: string; // Proactive alert ID for acknowledgment
}

export interface Conversation {
  id: string;
  title: string;
  messages: Message[];
  updatedAt: Date;
}

export interface SuggestedQuestion {
  icon: string;
  text: string;
  category: string;
}

@Component({
  selector: 'app-chatbot-page',
  standalone: true,
  imports: [CommonModule, FormsModule],
  templateUrl: './chatbot-page.html',
  styleUrl: './chatbot-page.css',
})
export class ChatbotPageComponent {
  // UI States
  isSidebarOpen = signal(true);
  webSearchEnabled = signal(false);
  agentModeEnabled = signal(false);
  activeLanguage = signal<'fr' | 'ar' | 'en' | 'darija'>(this.getSystemLanguage());
  
  conversations = signal<Conversation[]>([]);
  activeConversationId = signal<string>('');
  inputText = '';
  isTyping = signal(false);
  suggestedQuestions = signal<SuggestedQuestion[]>([]);
  hasUnacknowledgedProactiveAlert = signal(false);

  activeConversation = signal<Conversation | undefined>(undefined);

  private apiService = inject(ApiService);
  private chatbotWs = inject(ChatbotWsService);
  private proactiveSub?: Subscription;

  constructor() {
    effect(() => {
      const conv = this.conversations().find(c => c.id === this.activeConversationId());
      this.activeConversation.set(conv);
    }, { allowSignalWrites: true });
  }

  ngOnInit() {
    this.loadSessions();
    this.loadSuggestedQuestions();
    this.connectProactiveWebSocket();
    this.loadPendingProactiveAlerts();
  }

  ngOnDestroy() {
    this.proactiveSub?.unsubscribe();
    this.chatbotWs.disconnect();
  }

  /** Connect to the proactive chatbot WebSocket for real-time alerts. */
  private connectProactiveWebSocket() {
    this.chatbotWs.connect();
    this.proactiveSub = this.chatbotWs.proactiveAlerts$.subscribe((alert) => {
      this.handleProactiveAlert(alert);
    });
  }

  /** Load any pending proactive alerts from the backend (for when user opens chatbot page). */
  private loadPendingProactiveAlerts() {
    this.apiService.getProactiveAlerts().subscribe({
      next: (alerts) => {
        if (alerts && alerts.length > 0) {
          this.hasUnacknowledgedProactiveAlert.set(true);
          // Inject the most recent proactive alert as a message
          const latest = alerts[0];
          this.injectProactiveMessage(latest);
        }
      },
      error: (err) => console.error('Failed to load proactive alerts', err)
    });
  }

  /** Handle a real-time proactive alert from WebSocket. */
  private handleProactiveAlert(alert: ProactiveAlertPayload) {
    this.hasUnacknowledgedProactiveAlert.set(true);
    this.injectProactiveMessage({
      id: alert.alert_id,
      session_id: alert.session_id,
      message_id: alert.message_id,
      content: alert.content,
      trigger_count: alert.trigger_count,
      categories: alert.categories,
    });
  }

  /** Inject a proactive message into the chatbot conversation. */
  private injectProactiveMessage(alert: { id: string; session_id: string; message_id: string; content: string; trigger_count: number; categories: string[] }) {
    const proactiveMsg: Message = {
      id: crypto.randomUUID(),
      role: 'bot',
      text: alert.content,
      timestamp: new Date(),
      serverMessageId: alert.message_id,
      isProactive: true,
      proactiveAlertId: alert.id,
    };

    // Create a new conversation for the proactive alert if no active conversation exists
    const currentConv = this.activeConversation();
    if (!currentConv || currentConv.messages.length === 0) {
      const newConv: Conversation = {
        id: alert.session_id || 'proactive-' + alert.id,
        title: `🛡️ Alerte proactive (${alert.trigger_count} messages signalés)`,
        messages: [proactiveMsg],
        updatedAt: new Date()
      };
      this.conversations.update(prev => [newConv, ...prev]);
      this.activeConversationId.set(newConv.id);
    } else {
      // Inject into the active conversation
      this.updateMessages(proactiveMsg);
    }

    this.scrollToBottom();
  }

  /** Dismiss a proactive alert. */
  dismissProactiveAlert(alertId: string) {
    this.apiService.acknowledgeProactiveAlert(alertId).subscribe({
      next: () => {
        this.hasUnacknowledgedProactiveAlert.set(false);
      },
      error: (err) => console.error('Failed to acknowledge proactive alert', err)
    });
  }

  loadSessions() {
    this.apiService.getChatSessions().subscribe({
      next: (sessions) => {
        // Convert API dates back to Date objects
        const formattedSessions = sessions.map(s => ({
          ...s,
          updatedAt: new Date(s.updatedAt),
          messages: s.messages.map((m: any) => ({
            ...m,
            timestamp: new Date(m.timestamp),
            serverMessageId: m.role === 'bot' ? m.id : undefined,
            feedback: m.feedback || 'none',
            isProactive: m.isProactive || false,
          }))
        }));
        
        this.conversations.set(formattedSessions);
        if (formattedSessions.length > 0 && !this.activeConversationId()) {
          this.activeConversationId.set(formattedSessions[0].id);
        } else if (formattedSessions.length === 0) {
          this.newChat();
        }
      },
      error: (err) => console.error('Failed to load chat sessions', err)
    });
  }

  private getSystemLanguage(): 'fr' | 'ar' | 'en' | 'darija' {
    const lang = navigator.language.split('-')[0];
    if (['fr', 'ar', 'en'].includes(lang)) return lang as any;
    // Default to French (most common in Morocco); Darija can be selected manually
    return 'fr';
  }

  loadSuggestedQuestions() {
    this.apiService.getSuggestedQuestions(this.activeLanguage()).subscribe({
      next: (questions) => this.suggestedQuestions.set(questions),
      error: (err) => console.error('Failed to load suggested questions', err)
    });
  }

  shouldShowSuggestions(): boolean {
    const conv = this.activeConversation();
    if (!conv) return true;
    // Show suggestions only when there's just the welcome message (or no messages)
    const userMessages = conv.messages.filter(m => m.role === 'user');
    return userMessages.length === 0;
  }

  askSuggested(question: string) {
    if (this.isTyping()) return;
    this.inputText = question;
    this.sendMessage();
  }

  selectConversation(id: string) {
    this.activeConversationId.set(id);
  }

  newChat() {
    const newConv: Conversation = {
      id: 'temp-' + Math.random().toString(36).substring(7),
      title: 'Nouvelle conversation',
      messages: [],
      updatedAt: new Date()
    };
    
    this.conversations.update(prev => [newConv, ...prev]);
    this.activeConversationId.set(newConv.id);
  }

  deleteConversation(id: string, event?: Event) {
    if (event) event.stopPropagation();
    
    // Optimistically update UI
    this.conversations.update(prev => prev.filter(c => c.id !== id));
    
    // If we deleted the active conversation, switch to the first available one or create new
    if (this.activeConversationId() === id) {
      const remaining = this.conversations();
      if (remaining.length > 0) {
        this.activeConversationId.set(remaining[0].id);
      } else {
        this.activeConversationId.set('');
        this.newChat();
      }
    }

    // Call API (only if it's a real UUID from the backend, not a temporary new chat ID)
    if (!id.startsWith('temp-')) {
      this.apiService.deleteChatSession(id).subscribe({
        error: (err) => console.error('Failed to delete session', err)
      });
    }
  }

  sendMessage() {
    if (!this.inputText.trim() || this.isTyping()) return;

    const userText = this.inputText;
    this.inputText = '';
    
    const userMsg: Message = {
      id: crypto.randomUUID(),
      role: 'user',
      text: userText,
      timestamp: new Date()
    };

    this.updateMessages(userMsg);
    this.simulateResponse(userText);
  }

  private updateMessages(msg: Message) {
    this.conversations.update(prev => prev.map(c => {
      if (c.id === this.activeConversationId()) {
        const updatedMessages = [...c.messages, msg];
        let title = c.title;
        if (c.title === 'Nouvelle conversation' && msg.role === 'user') {
          title = msg.text.substring(0, 30) + (msg.text.length > 30 ? '...' : '');
        }
        return { ...c, messages: updatedMessages, title, updatedAt: new Date() };
      }
      return c;
    }));
  }

  private simulateResponse(query: string) {
    this.isTyping.set(true);
    
    // Default fallback steps
    let steps: ThinkingStep[] = [
      { label: 'Recherche dans la base de connaissance...', status: 'running' }
    ];

    const botMsgId = crypto.randomUUID();
    const botMsg: Message = {
      id: botMsgId,
      role: 'bot',
      text: '',
      timestamp: new Date(),
      thinkingSteps: this.agentModeEnabled() ? steps : undefined
    };

    this.updateMessages(botMsg);

    // A real UUID from the backend is 36 characters. The temporary ID we generate is ~6-7 chars.
    const currentId = this.activeConversationId();
    const isNewSession = currentId.length < 20; 
    const sessionId = isNewSession ? undefined : currentId;
    
    // Use SSE streaming for real-time response delivery
    let accumulatedText = '';
    let receivedSessionId = sessionId || currentId;
    let receivedMessageId: string | undefined;
    let receivedSources: Source[] = [];

    this.apiService.askChatbotStream(query, sessionId, this.activeLanguage()).subscribe({
      next: (event) => {
        switch (event.type) {
          case 'thinking':
            if (this.agentModeEnabled()) {
              this.conversations.update(prev => prev.map(c => {
                if (c.id === this.activeConversationId()) {
                  return {
                    ...c,
                    messages: c.messages.map(m => {
                      if (m.id === botMsgId) {
                        const updatedSteps = [...(m.thinkingSteps || []), event.data];
                        return { ...m, thinkingSteps: updatedSteps };
                      }
                      return m;
                    })
                  };
                }
                return c;
              }));
            }
            break;

          case 'answer_chunk':
            accumulatedText += event.data;
            this.updateBotText(botMsgId, accumulatedText);
            this.scrollToBottom();
            break;

          case 'done':
            // Update session ID if new session
            if (isNewSession && event.data.session_id) {
              this.conversations.update(prev => prev.map(c =>
                c.id === this.activeConversationId() ? { ...c, id: event.data.session_id } : c
              ));
              this.activeConversationId.set(event.data.session_id);
              receivedSessionId = event.data.session_id;
            }
            receivedMessageId = event.data.message_id;
            receivedSources = event.data.sources || [];

            // Finalize the message with sources and metadata
            this.conversations.update(prev => prev.map(c => {
              if (c.id === this.activeConversationId()) {
                return {
                  ...c,
                  messages: c.messages.map(m =>
                    m.id === botMsgId ? {
                      ...m,
                      text: accumulatedText,
                      sources: receivedSources,
                      serverMessageId: receivedMessageId,
                    } : m
                  )
                };
              }
              return c;
            }));
            this.isTyping.set(false);
            this.scrollToBottom();
            break;

          case 'error':
            this.finalizeBotMessage(botMsgId, `Erreur: ${event.data}`, []);
            break;
        }
      },
      error: (err) => {
        console.error(err);
        // Fallback to non-streaming endpoint on SSE failure
        this.apiService.askChatbot(query, isNewSession ? undefined : currentId, this.activeLanguage()).subscribe({
          next: (res) => {
            if (isNewSession && res.session_id) {
              this.conversations.update(prev => prev.map(c =>
                c.id === this.activeConversationId() ? { ...c, id: res.session_id } : c
              ));
              this.activeConversationId.set(res.session_id);
            }
            if (res.thinking_steps && this.agentModeEnabled()) {
              this.conversations.update(prev => prev.map(c => {
                if (c.id === this.activeConversationId()) {
                  return {
                    ...c,
                    messages: c.messages.map(m => m.id === botMsgId ? {...m, thinkingSteps: res.thinking_steps} : m)
                  };
                }
                return c;
              }));
            }
            if (res.message_id) {
              this.conversations.update(prev => prev.map(c => {
                if (c.id === this.activeConversationId()) {
                  return {
                    ...c,
                    messages: c.messages.map(m => m.id === botMsgId ? {...m, serverMessageId: res.message_id} : m)
                  };
                }
                return c;
              }));
            }
            this.finalizeBotMessage(botMsgId, res.answer, res.sources);
          },
          error: () => {
            this.finalizeBotMessage(botMsgId, "Erreur de connexion au serveur RAG. Veuillez réessayer.", []);
          }
        });
      }
    });
  }

  private finalizeBotMessage(msgId: string, responseText: string, sources: Source[]) {

    // Start streaming words
    let currentText = '';
    const words = responseText.split(' ');
    let i = 0;

    const interval = setInterval(() => {
      if (i < words.length) {
        currentText += (i === 0 ? '' : ' ') + words[i];
        this.updateBotText(msgId, currentText);
        this.scrollToBottom();
        i++;
      } else {
        clearInterval(interval);
        // Finalize with sources
        this.conversations.update(prev => prev.map(c => {
          if (c.id === this.activeConversationId()) {
            const msgs = c.messages.map(m => {
              if (m.id === msgId) {
                return { ...m, text: currentText, sources };
              }
              return m;
            });
            return { ...c, messages: msgs };
          }
          return c;
        }));
        this.isTyping.set(false);
        this.scrollToBottom();
      }
    }, 40);
  }

  private updateBotText(msgId: string, text: string) {
    this.conversations.update(prev => prev.map(c => {
      if (c.id === this.activeConversationId()) {
        const msgs = c.messages.map(m => {
          if (m.id === msgId) {
            return { ...m, text };
          }
          return m;
        });
        return { ...c, messages: msgs };
      }
      return c;
    }));
  }

  private scrollToBottom() {
    setTimeout(() => {
      const el = document.getElementById('chat-scroll-container');
      if (el) el.scrollTop = el.scrollHeight;
    }, 60);
  }

  getGroupedConversations() {
    const now = new Date();
    const today = this.conversations().filter(c => this.isSameDay(c.updatedAt, now));
    const yesterday = this.conversations().filter(c => this.isYesterday(c.updatedAt, now));
    const older = this.conversations().filter(c => !this.isSameDay(c.updatedAt, now) && !this.isYesterday(c.updatedAt, now));
    
    return [
      { label: 'Aujourd\'hui', chats: today },
      { label: 'Hier', chats: yesterday },
      { label: 'Anciens', chats: older }
    ].filter(g => g.chats.length > 0);
  }

  private isSameDay(d1: Date, d2: Date) {
    return d1.getFullYear() === d2.getFullYear() && d1.getMonth() === d2.getMonth() && d1.getDate() === d2.getDate();
  }

  private isYesterday(d1: Date, d2: Date) {
    const yesterday = new Date(d2);
    yesterday.setDate(yesterday.getDate() - 1);
    return this.isSameDay(d1, yesterday);
  }

  // ══════════════════════════════════════════════════════════════
  //  FEEDBACK (Thumbs Up/Down)
  // ══════════════════════════════════════════════════════════════

  submitFeedback(msgId: string, feedback: 'up' | 'down') {
    // Find the message to get the serverMessageId
    const conv = this.activeConversation();
    if (!conv) return;

    const msg = conv.messages.find(m => m.id === msgId);
    if (!msg) return;

    // Use serverMessageId for backend feedback, or the message id if loaded from DB
    const serverId = msg.serverMessageId || msg.id;
    if (!serverId) return;

    // Optimistically update UI
    this.conversations.update(prev => prev.map(c => {
      if (c.id === this.activeConversationId()) {
        return {
          ...c,
          messages: c.messages.map(m =>
            m.id === msgId ? { ...m, feedback: m.feedback === feedback ? 'none' : feedback } : m
          )
        };
      }
      return c;
    }));

    // Send to backend — toggle off if same button clicked again
    const finalFeedback: 'up' | 'down' | 'none' = msg.feedback === feedback ? 'none' : feedback;
    this.apiService.submitMessageFeedback(serverId, finalFeedback).subscribe({
      error: (err) => console.error('Feedback failed', err)
    });
  }
}
