# Generated by Django 5.2.12 on 2026-04-09 00:45

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('contact_jid', models.CharField(help_text='WhatsApp JID of the external contact (the sender)', max_length=255)),
                ('contact_name', models.CharField(blank=True, default='', help_text='Push name or saved contact name', max_length=255)),
                ('platform', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('telegram', 'Telegram'), ('simulated', 'Simulated')], default='whatsapp', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Conversation',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='HarassmentCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Internal code: verbal_harassment, threat, sexual_harassment, discrimination, repeated_messages, identity_theft, safe', max_length=30, unique=True)),
                ('label_fr', models.CharField(help_text='French label', max_length=100)),
                ('label_ar', models.CharField(help_text='Arabic label', max_length=100)),
                ('label_en', models.CharField(help_text='English label', max_length=100)),
                ('severity_weight', models.FloatField(default=1.0, help_text='Severity multiplier for score weighting (e.g., threat=1.5, safe=0.0)')),
                ('description', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name': 'Harassment Category',
                'verbose_name_plural': 'Harassment Categories',
                'ordering': ['-severity_weight'],
            },
        ),
        migrations.CreateModel(
            name='MonitoredChild',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(help_text="Child's display name", max_length=255)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('school_name', models.CharField(blank=True, default='', max_length=255)),
                ('school_level', models.CharField(blank=True, choices=[('primaire', 'Primaire'), ('college', 'Collège'), ('lycee', 'Lycée'), ('universite', 'Université')], default='', max_length=20)),
                ('whatsapp_jid', models.CharField(help_text='WhatsApp JID (e.g., 212612345678@s.whatsapp.net)', max_length=255, unique=True)),
                ('whatsapp_display_number', models.CharField(blank=True, default='', help_text='Formatted display number (e.g., +212 6XX XXX X01)', max_length=30)),
                ('is_monitored', models.BooleanField(default=True)),
                ('linked_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Monitored Child',
                'verbose_name_plural': 'Monitored Children',
            },
        ),
        migrations.CreateModel(
            name='UserBehaviorProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_jid', models.CharField(max_length=255, unique=True)),
                ('total_messages_sent', models.IntegerField(default=0)),
                ('total_blocked_messages_sent', models.IntegerField(default=0, help_text='Messages sent by this user that were blocked')),
                ('total_blocked_messages_received', models.IntegerField(default=0, help_text='Blocked messages received by this user (victim metric)')),
                ('block_ratio', models.FloatField(default=0.0, help_text='Ratio of blocked to total messages (0.0 - 1.0)')),
                ('average_toxicity_score', models.FloatField(default=0.0)),
                ('escalation_count', models.IntegerField(default=0, help_text='Number of ESCALATE decisions for this user')),
                ('night_activity_ratio', models.FloatField(default=0.0, help_text='Ratio of messages sent between 22h-06h')),
                ('unique_targets_count', models.IntegerField(default=0, help_text='Number of different people this user has harassed (harasser profiling)')),
                ('repeated_harassers_count', models.IntegerField(default=0, help_text='Number of distinct harassers who targeted this user 3+ times (victim profiling)')),
                ('risk_score', models.FloatField(default=0.0)),
                ('risk_level', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='LOW', max_length=20)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'User Behavior Profile',
            },
        ),
        migrations.CreateModel(
            name='AegisUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('admin', 'Administrator'), ('parent', 'Parent / Guardian')], default='parent', max_length=20)),
                ('language_preference', models.CharField(default='fr', help_text='UI language: fr, ar, en', max_length=5)),
                ('phone_number', models.CharField(blank=True, default='', help_text='Primary phone for notifications', max_length=20)),
                ('auto_protection_enabled', models.BooleanField(default=False, help_text='Adult self-protection mode (monitors own messages)')),
                ('notification_email', models.CharField(blank=True, default='', help_text='Separate email for alert notifications', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'AEGIS User',
                'verbose_name_plural': 'AEGIS Users',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('language', models.CharField(default='fr', help_text='Session language: fr, ar, en', max_length=5)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(blank=True, help_text='Authenticated user who started this session (null for anonymous)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Chat Session',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant')], max_length=10)),
                ('content', models.TextField(help_text='Message content')),
                ('retrieved_context', models.TextField(blank=True, default='', help_text='RAG context chunks retrieved for this response')),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='moderation.chatsession')),
            ],
            options={
                'verbose_name': 'Chat Message',
                'ordering': ['sent_at'],
            },
        ),
        migrations.CreateModel(
            name='ModerationResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('instance_name', models.CharField(help_text='Evolution API instance name', max_length=255)),
                ('sender_jid', models.CharField(help_text='WhatsApp ID of the sender', max_length=255)),
                ('raw_text', models.TextField(help_text='Original message text')),
                ('normalized_text', models.TextField(help_text='Message text after V3 normalization')),
                ('language', models.CharField(default='en', help_text='Detected language (e.g. en, fr, ar, darija)', max_length=20)),
                ('message_key_id', models.CharField(blank=True, help_text='Evolution API message key for deletion', max_length=255, null=True)),
                ('primary_class', models.CharField(blank=True, help_text='M2 detected category (e.g. threat, sexual_harassment)', max_length=50, null=True)),
                ('toxicity_score', models.FloatField(help_text='M1 toxicity score (0-1)')),
                ('confidence_score', models.FloatField(blank=True, help_text='M2 specialist confidence score (NULL for ALLOW)', null=True)),
                ('behavioral_risk_score', models.FloatField(default=0.0, help_text='Agent 4 score')),
                ('final_score', models.FloatField(help_text='Combined final score')),
                ('processing_time_ms', models.IntegerField(default=0, help_text='Total pipeline processing time in milliseconds')),
                ('decision', models.CharField(choices=[('ALLOW', 'Allow'), ('WARN', 'Warn'), ('BLOCK', 'Block'), ('ESCALATE', 'Escalate'), ('REVISE', 'Revise'), ('HUMAN_REVIEW', 'Human Review')], default='ALLOW', max_length=20)),
                ('llm_triggered', models.BooleanField(default=False)),
                ('llm_explanation', models.TextField(blank=True, null=True)),
                ('flagged_for_review', models.BooleanField(default=False, help_text='Admin flagged this message (even ALLOW) for manual review')),
                ('human_reviewed', models.BooleanField(default=False, help_text='A human admin has reviewed and overridden the AI decision')),
                ('human_decision', models.CharField(blank=True, help_text="Admin's override decision (BLOCK/WARN/ALLOW/etc.)", max_length=20, null=True)),
                ('human_label', models.CharField(blank=True, help_text="Admin's corrected category (e.g. sexual_harassment)", max_length=50, null=True)),
                ('human_note', models.TextField(blank=True, help_text='Optional admin note on the override', null=True)),
                ('human_reviewed_at', models.DateTimeField(blank=True, help_text='Timestamp of when the human reviewed this message', null=True)),
                ('original_ai_decision', models.CharField(blank=True, help_text="AI's original decision before human override", max_length=20, null=True)),
                ('original_ai_label', models.CharField(blank=True, help_text="AI's original class label before human override", max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(blank=True, help_text='Reference to the harassment category lookup table', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderation_results', to='moderation.harassmentcategory')),
                ('reviewed_by', models.ForeignKey(blank=True, help_text='The admin who performed the human review', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_moderations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Moderation Result',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField(help_text='Message content (plaintext for prototype)')),
                ('content_hash', models.CharField(blank=True, default='', help_text='SHA-256 hash of the message content', max_length=64)),
                ('language', models.CharField(default='unknown', help_text='Detected language (fr, ar, en, darija, unknown)', max_length=20)),
                ('is_displayed', models.BooleanField(default=True, help_text='Whether the message is visible to the child')),
                ('is_blocked', models.BooleanField(default=False, help_text='Whether the AI blocked this message')),
                ('platform', models.CharField(default='whatsapp', max_length=20)),
                ('platform_message_id', models.CharField(blank=True, default='', help_text='Original platform message ID (Evolution API key.id)', max_length=255)),
                ('sender_jid', models.CharField(help_text='WhatsApp JID of the sender', max_length=255)),
                ('sent_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('conversation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='moderation.conversation')),
                ('moderation_result', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='message', to='moderation.moderationresult')),
            ],
            options={
                'verbose_name': 'Message',
                'ordering': ['-sent_at'],
            },
        ),
        migrations.AddField(
            model_name='conversation',
            name='child',
            field=models.ForeignKey(blank=True, help_text='The monitored child this conversation belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='moderation.monitoredchild'),
        ),
        migrations.CreateModel(
            name='ParentProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('alert_threshold', models.FloatField(default=0.65, help_text='Minimum score to trigger a parent alert (0.0 - 1.0)')),
                ('receive_sms_alerts', models.BooleanField(default=True)),
                ('receive_email_alerts', models.BooleanField(default=True)),
                ('receive_push_alerts', models.BooleanField(default=True)),
                ('receive_call_on_critical', models.BooleanField(default=True, help_text='Automatic phone call for CRITICAL severity alerts')),
                ('evolution_instance_name', models.CharField(blank=True, help_text="Evolution API instance name for this parent's WhatsApp bridge", max_length=255, null=True)),
                ('evolution_connected', models.BooleanField(default=False, help_text='Whether the Evolution API instance is currently connected')),
                ('evolution_connected_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='parent_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Parent Profile',
            },
        ),
        migrations.AddField(
            model_name='monitoredchild',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to='moderation.parentprofile'),
        ),
        migrations.CreateModel(
            name='SecurityAlert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('alert_type', models.CharField(choices=[('push', 'Push Notification'), ('email', 'Email'), ('sms', 'SMS'), ('call', 'Phone Call')], default='push', help_text='Notification delivery channel', max_length=10)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20)),
                ('message_preview', models.CharField(max_length=255)),
                ('is_read', models.BooleanField(default=False)),
                ('is_resolved', models.BooleanField(default=False)),
                ('parent_notified', models.BooleanField(default=False, help_text='External notification (SMS/email/call) was sent to parent')),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('moderation_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='moderation.moderationresult')),
                ('recipient', models.ForeignKey(blank=True, help_text='User who should receive this alert (parent or admin)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_alerts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Security Alert',
                'ordering': ['-sent_at'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='conversation',
            unique_together={('child', 'contact_jid')},
        ),
        migrations.CreateModel(
            name='BehavioralSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_snapshot', models.DateField(help_text='Date this snapshot was taken')),
                ('message_count', models.IntegerField(default=0)),
                ('blocked_count', models.IntegerField(default=0)),
                ('risk_score_snapshot', models.FloatField(default=0.0)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='moderation.userbehaviorprofile')),
            ],
            options={
                'verbose_name': 'Behavioral Snapshot',
                'ordering': ['-date_snapshot'],
                'unique_together': {('profile', 'date_snapshot')},
            },
        ),
    ]
