# Generated by Django 5.2.12 on 2026-04-05 16:01

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModerationResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('instance_name', models.CharField(help_text='Evolution API instance name', max_length=255)),
                ('sender_jid', models.CharField(help_text='WhatsApp ID of the sender', max_length=255)),
                ('raw_text', models.TextField(help_text='Original message text')),
                ('normalized_text', models.TextField(help_text='Message text after V3 normalization')),
                ('toxicity_score', models.FloatField(help_text='M1 toxicity score (0-1)')),
                ('confidence_score', models.FloatField(help_text='M2 specialist confidence score')),
                ('behavioral_risk_score', models.FloatField(default=0.0, help_text='Agent 4 score')),
                ('final_score', models.FloatField(help_text='Combined final score')),
                ('decision', models.CharField(choices=[('ALLOW', 'Allow'), ('WARN', 'Warn'), ('BLOCK', 'Block'), ('CRITIQUE', 'Critique'), ('REVISE', 'Revise')], default='ALLOW', max_length=20)),
                ('llm_triggered', models.BooleanField(default=False)),
                ('llm_explanation', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Moderation Result',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserBehaviorProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_jid', models.CharField(max_length=255, unique=True)),
                ('total_messages_sent', models.IntegerField(default=0)),
                ('total_blocked_messages', models.IntegerField(default=0)),
                ('average_toxicity_score', models.FloatField(default=0.0)),
                ('risk_score', models.FloatField(default=0.0)),
                ('risk_level', models.CharField(default='LOW', help_text='LOW / MEDIUM / HIGH / CRITICAL', max_length=20)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'User Behavior Profile',
            },
        ),
        migrations.CreateModel(
            name='SecurityAlert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('severity', models.CharField(max_length=20)),
                ('message_preview', models.CharField(max_length=255)),
                ('is_read', models.BooleanField(default=False)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('moderation_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='moderation.moderationresult')),
            ],
            options={
                'verbose_name': 'Security Alert',
                'ordering': ['-sent_at'],
            },
        ),
    ]
