# Generated by Django 5.2.12 on 2026-04-07 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moderation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='moderationresult',
            name='message_key_id',
            field=models.CharField(blank=True, help_text='Evolution API message key for deletion', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='moderationresult',
            name='decision',
            field=models.CharField(choices=[('ALLOW', 'Allow'), ('WARN', 'Warn'), ('BLOCK', 'Block'), ('ESCALATE', 'Escalate'), ('REVISE', 'Revise')], default='ALLOW', max_length=20),
        ),
    ]
