# Generated by Django 5.2.12 on 2026-04-13 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moderation', '0002_seed_harassment_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='moderationresult',
            name='is_from_me',
            field=models.BooleanField(default=False, help_text='True if the monitored child sent this message'),
        ),
        migrations.AddField(
            model_name='moderationresult',
            name='sender_name',
            field=models.CharField(blank=True, help_text='Push name or display name of the sender', max_length=255, null=True),
        ),
    ]
