# Generated by Django 5.2.12 on 2026-04-08 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moderation', '0002_moderationresult_message_key_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='moderationresult',
            name='primary_class',
            field=models.CharField(blank=True, help_text='M2 detected category (e.g. threat, sexual_harassment)', max_length=50, null=True),
        ),
    ]
