# Generated by Django 5.2.12 on 2026-04-16 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moderation', '0003_moderationresult_is_from_me_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='moderationresult',
            name='ml_corrected',
            field=models.BooleanField(default=False, help_text="True when Agent 3 (Auditor) overrode the ML model's decision. Use to build retraining dataset."),
        ),
        migrations.AddField(
            model_name='moderationresult',
            name='ml_original_class',
            field=models.CharField(blank=True, help_text="The raw ML category BEFORE Agent 3 corrected it (e.g. 'threat' overridden to 'safe')", max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='moderationresult',
            name='ml_original_decision',
            field=models.CharField(blank=True, help_text='The raw ML decision BEFORE Agent 3 corrected it (e.g. BLOCK/ESCALATE overridden to ALLOW)', max_length=20, null=True),
        ),
    ]
