# Generated by Django 5.2.12 on 2026-04-17 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moderation', '0004_moderationresult_ml_corrected_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbehaviorprofile',
            name='avg_message_length',
            field=models.FloatField(default=0.0, help_text='Typical message length'),
        ),
        migrations.AddField(
            model_name='userbehaviorprofile',
            name='burst_count_24h',
            field=models.IntegerField(default=0, help_text='Number of burst episodes in 24h (5+ msgs in 10 mins)'),
        ),
        migrations.AddField(
            model_name='userbehaviorprofile',
            name='correction_rate',
            field=models.FloatField(default=0.0, help_text='How often Agent 3 overrides ML'),
        ),
        migrations.AddField(
            model_name='userbehaviorprofile',
            name='first_seen_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Account age', null=True),
        ),
        migrations.AddField(
            model_name='userbehaviorprofile',
            name='llm_triggers_total',
            field=models.IntegerField(default=0, help_text='Total times Agent 3 was triggered'),
        ),
        migrations.AddField(
            model_name='userbehaviorprofile',
            name='max_toxicity_24h',
            field=models.FloatField(default=0.0, help_text='Worst toxicity score today'),
        ),
        migrations.AddField(
            model_name='userbehaviorprofile',
            name='message_frequency_1h',
            field=models.FloatField(default=0.0, help_text='Messages in last hour'),
        ),
        migrations.AddField(
            model_name='userbehaviorprofile',
            name='ml_corrections_total',
            field=models.IntegerField(default=0, help_text='Total ML overrides by Agent 3'),
        ),
    ]
