# Generated by Django 5.2.12 on 2026-04-19 17:31

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moderation', '0005_userbehaviorprofile_avg_message_length_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockedContact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sender_jid', models.CharField(help_text='WhatsApp JID of the blocked contact', max_length=255, unique=True)),
                ('instance_name', models.CharField(help_text='Evolution API instance where the block was triggered', max_length=255)),
                ('reason', models.CharField(default='BLOCK', help_text='Why the contact was blocked (BLOCK, ESCALATE, MANUAL)', max_length=50)),
                ('blocked_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True, help_text='Set to False to unblock a contact')),
            ],
            options={
                'verbose_name': 'Blocked Contact',
                'verbose_name_plural': 'Blocked Contacts',
                'ordering': ['-blocked_at'],
            },
        ),
    ]
