# Generated by Django 5.2.12 on 2026-04-22 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moderation', '0006_blockedcontact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userbehaviorprofile',
            name='correction_rate',
        ),
        migrations.RemoveField(
            model_name='userbehaviorprofile',
            name='ml_corrections_total',
        ),
        migrations.AddField(
            model_name='userbehaviorprofile',
            name='downward_corrections_total',
            field=models.IntegerField(default=0, help_text='Times Agent 3 de-escalated ML decision'),
        ),
        migrations.AddField(
            model_name='userbehaviorprofile',
            name='upward_corrections_total',
            field=models.IntegerField(default=0, help_text='Times Agent 3 escalated ML decision'),
        ),
    ]
