# Generated by Django 5.2.12 on 2026-04-22 20:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moderation', '0007_remove_userbehaviorprofile_correction_rate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbehaviorprofile',
            name='first_seen_at',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Account age (can be backdated via WhatsApp history)', null=True),
        ),
    ]
