# Generated by Django 5.2.12 on 2026-04-22 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moderation', '0008_alter_userbehaviorprofile_first_seen_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbehaviorprofile',
            name='is_saved_contact',
            field=models.BooleanField(default=False, help_text='Is this person saved in the WhatsApp phonebook?'),
        ),
    ]
