# Generated by Django 5.2.12 on 2026-04-23 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moderation', '0009_userbehaviorprofile_is_saved_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userbehaviorprofile',
            name='is_saved_contact',
        ),
        migrations.AddField(
            model_name='userbehaviorprofile',
            name='child_initiated',
            field=models.BooleanField(default=False, help_text='True if the child sent the very first message in the relationship'),
        ),
        migrations.AddField(
            model_name='userbehaviorprofile',
            name='shared_groups_count',
            field=models.IntegerField(default=0, help_text='Number of shared WhatsApp groups (synced by background task)'),
        ),
    ]
