# Generated by Django 5.2.12 on 2026-04-23 02:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moderation', '0010_remove_userbehaviorprofile_is_saved_contact_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('report_type', models.CharField(choices=[('summary', 'Summary'), ('full', 'Full Analysis'), ('legal', 'Legal Evidence'), ('intelligence', 'Intelligence Brief')], max_length=20)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('generating', 'Generating'), ('ready', 'Ready'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('delivery_channel', models.CharField(choices=[('email', 'Email'), ('whatsapp', 'WhatsApp'), ('both', 'Email & WhatsApp'), ('dashboard', 'Dashboard Only')], default='dashboard', max_length=20)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='reports/')),
                ('ai_narrative', models.TextField(blank=True, default='')),
                ('stats_json', models.JSONField(blank=True, default=dict)),
                ('flagged_legal', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('child', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='moderation.monitoredchild')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Report',
                'verbose_name_plural': 'Reports',
                'ordering': ['-created_at'],
            },
        ),
    ]
