# Generated by Django 5.2.12 on 2026-04-25 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moderation', '0011_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='behavioralsnapshot',
            name='alert_id',
            field=models.CharField(blank=True, help_text='SecurityAlert ID that triggered this snapshot update', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='behavioralsnapshot',
            name='archetype',
            field=models.CharField(default='Normal User', help_text='BN archetype classification (Normal User, Groomer Pattern, Bully Pattern, Troll Pattern)', max_length=40),
        ),
        migrations.AddField(
            model_name='behavioralsnapshot',
            name='bully_prob',
            field=models.FloatField(default=0.0, help_text='P(BullyRisk=HIGH) from Bayesian inference'),
        ),
        migrations.AddField(
            model_name='behavioralsnapshot',
            name='grooming_prob',
            field=models.FloatField(default=0.0, help_text='P(GroomingRisk=HIGH) from Bayesian inference'),
        ),
        migrations.AddField(
            model_name='behavioralsnapshot',
            name='risk_level',
            field=models.CharField(default='LOW', help_text='BN-inferred risk level (LOW/MEDIUM/HIGH/CRITICAL)', max_length=20),
        ),
        migrations.AddField(
            model_name='behavioralsnapshot',
            name='troll_prob',
            field=models.FloatField(default=0.0, help_text='P(TrollRisk=HIGH) from Bayesian inference'),
        ),
    ]
