# Generated by Django 5.2.12 on 2026-04-25 00:40

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moderation', '0012_add_bayesian_fields_to_behavioral_snapshot'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ai_warn_threshold', models.FloatField(default=0.5)),
                ('ai_review_threshold', models.FloatField(default=0.65)),
                ('ai_block_threshold', models.FloatField(default=0.75)),
                ('ai_critical_threshold', models.FloatField(default=0.9)),
                ('agent_1_enabled', models.BooleanField(default=True, help_text='Regex Gate')),
                ('agent_2_enabled', models.BooleanField(default=True, help_text='ML Classification')),
                ('agent_3_enabled', models.BooleanField(default=True, help_text='Semantic LLM')),
                ('agent_4_enabled', models.BooleanField(default=True, help_text='Behavioral Engine')),
                ('agent_5_enabled', models.BooleanField(default=True, help_text='Decision Orchestrator')),
                ('active_llm_provider', models.CharField(default='groq', max_length=50)),
                ('active_llm_model', models.CharField(default='llama3-70b-8192', max_length=100)),
                ('log_retention_days', models.IntegerField(default=30)),
                ('message_retention_days', models.IntegerField(default=90)),
                ('alert_retention_days', models.IntegerField(default=365)),
                ('strictness_level', models.CharField(default='balanced', max_length=20)),
                ('auto_escalate', models.BooleanField(default=True)),
                ('block_unknown', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Platform Settings',
                'verbose_name_plural': 'Platform Settings',
            },
        ),
    ]
