# Generated by Django 5.2.12 on 2026-04-26 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moderation', '0013_add_platform_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='behavioralsnapshot',
            name='peak_risk_score',
            field=models.FloatField(default=0.0, help_text='Highest risk score observed today'),
        ),
        migrations.AddField(
            model_name='behavioralsnapshot',
            name='peak_risk_time',
            field=models.DateTimeField(blank=True, help_text='When the peak occurred', null=True),
        ),
        migrations.AddField(
            model_name='behavioralsnapshot',
            name='snapshot_count',
            field=models.IntegerField(default=0, help_text='Number of updates today'),
        ),
    ]
