# Generated by Django 5.2.12 on 2026-05-06 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moderation', '0014_behavioralsnapshot_peak_risk_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformsettings',
            name='auto_resolve_allow',
            field=models.BooleanField(default=True, help_text='Auto-resolve ALLOW decisions without admin review'),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='default_language',
            field=models.CharField(default='auto', help_text='Default detection language: auto, fr, ar, en', max_length=10),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='notify_email_enabled',
            field=models.BooleanField(default=True, help_text='Platform default: send email notifications on alerts'),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='notify_inapp_enabled',
            field=models.BooleanField(default=True, help_text='Platform default: show in-app notifications'),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='notify_on_block',
            field=models.BooleanField(default=True, help_text='Platform default: notify parent when a message is blocked'),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='notify_on_escalate',
            field=models.BooleanField(default=True, help_text='Platform default: notify parent on escalation'),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='notify_on_warn',
            field=models.BooleanField(default=False, help_text='Platform default: notify parent on warnings'),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='parent_portal_access',
            field=models.BooleanField(default=True, help_text='Allow parents to access the monitoring portal'),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='quiet_hours_end',
            field=models.CharField(default='07:00', help_text='End of quiet hours. Format: HH:MM', max_length=5),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='quiet_hours_start',
            field=models.CharField(default='23:00', help_text='Start of quiet hours (no notifications). Format: HH:MM', max_length=5),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='rate_limit_threshold',
            field=models.IntegerField(default=50, help_text='Max messages per hour per child before rate limiting'),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='risk_profile_retention_days',
            field=models.IntegerField(default=60, help_text='Days to keep behavioral snapshot history'),
        ),
    ]
