# Generated by Django 5.2.12 on 2026-05-06 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moderation', '0015_add_notification_moderation_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platformsettings',
            name='auto_resolve_allow',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='platformsettings',
            name='default_language',
            field=models.CharField(default='auto', max_length=10),
        ),
        migrations.AlterField(
            model_name='platformsettings',
            name='notify_email_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='platformsettings',
            name='notify_inapp_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='platformsettings',
            name='notify_on_block',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='platformsettings',
            name='notify_on_escalate',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='platformsettings',
            name='notify_on_warn',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='platformsettings',
            name='parent_portal_access',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='platformsettings',
            name='quiet_hours_end',
            field=models.CharField(default='07:00', max_length=5),
        ),
        migrations.AlterField(
            model_name='platformsettings',
            name='quiet_hours_start',
            field=models.CharField(default='23:00', max_length=5),
        ),
        migrations.AlterField(
            model_name='platformsettings',
            name='rate_limit_threshold',
            field=models.IntegerField(default=50),
        ),
        migrations.AlterField(
            model_name='platformsettings',
            name='risk_profile_retention_days',
            field=models.IntegerField(default=60),
        ),
    ]
