# Generated by Django 5.2.12 on 2026-05-08 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moderation', '0016_alter_platformsettings_auto_resolve_allow_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbehaviorprofile',
            name='shared_groups_metadata',
            field=models.JSONField(blank=True, default=list, help_text='Group details: [{group_jid, group_name, created_at, participant_count}, ...]'),
        ),
    ]
