# Generated by Django 5.2.12 on 2026-05-08 22:20

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moderation', '0017_add_shared_groups_metadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='moderationresult',
            name='is_self_moderation',
            field=models.BooleanField(default=False, help_text="True if this was a self-moderation event (child's own toxic message caught)"),
        ),
        migrations.AlterField(
            model_name='moderationresult',
            name='decision',
            field=models.CharField(choices=[('ALLOW', 'Allow'), ('WARN', 'Warn'), ('BLOCK', 'Block'), ('ESCALATE', 'Escalate'), ('REVISE', 'Revise'), ('HUMAN_REVIEW', 'Human Review'), ('EDUCATE', 'Educate')], default='ALLOW', max_length=20),
        ),
        migrations.CreateModel(
            name='SelfModerationEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(help_text="Category of the child's message (e.g., verbal_harassment, threat)", max_length=50)),
                ('original_decision', models.CharField(help_text='What the pipeline originally decided (BLOCK/WARN/ESCALATE) before converting to EDUCATE', max_length=20)),
                ('message_deleted', models.BooleanField(default=False, help_text='Whether the message was deleted for everyone')),
                ('educational_dm_sent', models.BooleanField(default=False, help_text='Whether the educational DM was sent via Aegis Assistant (Instance 2)')),
                ('educational_dm_text', models.TextField(blank=True, default='', help_text='The actual text of the educational DM sent to the child')),
                ('parent_notified', models.BooleanField(default=False, help_text='Whether the parent received a constructive notification')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('moderation_result', models.OneToOneField(help_text="The ModerationResult for the child's toxic message", on_delete=django.db.models.deletion.CASCADE, related_name='self_moderation_event', to='moderation.moderationresult')),
            ],
            options={
                'verbose_name': 'Self-Moderation Event',
                'verbose_name_plural': 'Self-Moderation Events',
                'ordering': ['-created_at'],
            },
        ),
    ]
