# Generated by Django 5.2.12 on 2026-05-09 01:19

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moderation', '0018_add_self_moderation'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotConversation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('child_jid', models.CharField(db_index=True, help_text='WhatsApp JID of the child', max_length=255)),
                ('role', models.CharField(choices=[('user', 'User (Child)'), ('assistant', 'Assistant (Bot)')], help_text="Who sent this message: 'user' (child) or 'assistant' (bot)", max_length=10)),
                ('content', models.TextField(help_text='The message text content')),
                ('is_safety_flagged', models.BooleanField(default=False, help_text='True if this message triggered a safety escalation')),
                ('threat_intel', models.JSONField(blank=True, help_text='Extracted threat intelligence: {threat_type, perpetrator, location, urgency, summary}', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Bot Conversation Message',
                'verbose_name_plural': 'Bot Conversation Messages',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['child_jid', 'created_at'], name='moderation__child_j_94a460_idx')],
            },
        ),
    ]
