# Generated by Django 5.2.12 on 2026-05-17 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moderation', '0019_bot_conversation_memory'),
    ]

    operations = [
        migrations.AddField(
            model_name='moderationresult',
            name='has_image',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='moderationresult',
            name='image_nsfw_detected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='moderationresult',
            name='image_nsfw_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='moderationresult',
            name='image_ocr_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='moderationresult',
            name='image_violence_detected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='moderationresult',
            name='image_violence_score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
