# Generated by Django 5.2.12 on 2026-05-18 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moderation', '0020_moderationresult_has_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='moderationresult',
            name='image_metadata',
            field=models.JSONField(blank=True, help_text='EXIF data like GPS, camera info', null=True),
        ),
    ]
