# Generated by Django 5.2.12 on 2026-05-19 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moderation', '0021_moderationresult_image_metadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='parentprofile',
            name='monitoring_mode',
            field=models.CharField(choices=[('child', 'Child Protection'), ('adult', 'Adult Self-Moderation')], default='child', help_text="Operating mode: 'child' = protect a minor, 'adult' = self-moderation", max_length=20),
        ),
        migrations.AddField(
            model_name='parentprofile',
            name='trusted_contact_name',
            field=models.CharField(blank=True, default='', help_text='Name of the trusted contact', max_length=100),
        ),
        migrations.AddField(
            model_name='parentprofile',
            name='trusted_contact_phone',
            field=models.CharField(blank=True, default='', help_text='Optional trusted contact for adult self-moderation critical alerts', max_length=20),
        ),
        migrations.AlterField(
            model_name='moderationresult',
            name='decision',
            field=models.CharField(choices=[('ALLOW', 'Allow'), ('WARN', 'Warn'), ('BLOCK', 'Block'), ('ESCALATE', 'Escalate'), ('REVISE', 'Revise'), ('HUMAN_REVIEW', 'Human Review'), ('EDUCATE', 'Educate'), ('SELF_WARN', 'Self Warning')], default='ALLOW', max_length=20),
        ),
    ]
