# Generated by Django 5.2.12 on 2026-05-28 22:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moderation', '0022_parentprofile_monitoring_mode_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndexedDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Original filename', max_length=255)),
                ('category', models.CharField(default='other', help_text='Document category: legal, guides, procedures, definitions, other', max_length=50)),
                ('language', models.CharField(default='fr', help_text='Document language: fr, ar, en', max_length=5)),
                ('chunk_count', models.IntegerField(default=0, help_text='Number of text chunks created from this document')),
                ('file_size', models.IntegerField(default=0, help_text='Original file size in bytes')),
                ('status', models.CharField(choices=[('processing', 'Processing'), ('indexed', 'Indexed'), ('failed', 'Failed')], default='processing', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Indexed Document',
                'verbose_name_plural': 'Indexed Documents',
                'ordering': ['-created_at'],
            },
        ),
    ]
