# Generated by Django 5.2.12 on 2026-05-29 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moderation', '0023_indexeddocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='source_type',
            field=models.CharField(default='knowledge_base', help_text='Where the answer came from: knowledge_base, web, hybrid', max_length=20),
        ),
    ]
