# Generated by Django 5.2.12 on 2026-06-05 20:37

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moderation', '0024_add_source_type_to_chatmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='FailedMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('raw_text', models.TextField(help_text='Original message text before pipeline processing')),
                ('sender_jid', models.CharField(help_text='WhatsApp JID of the sender', max_length=255)),
                ('instance_name', models.CharField(help_text='Evolution API instance that received the message', max_length=255)),
                ('message_key_id', models.CharField(blank=True, default='', help_text='WhatsApp message key for deduplication', max_length=255)),
                ('push_name', models.CharField(blank=True, default='', help_text='Display name of the sender', max_length=255)),
                ('error_type', models.CharField(help_text='Exception class name (e.g. TimeoutError, OperationalError)', max_length=255)),
                ('error_message', models.TextField(help_text='Full error traceback or message')),
                ('pipeline_stage', models.CharField(blank=True, default='', help_text='Which agent/stage was executing when the error occurred', max_length=100)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Extra context: image_analyzed, is_from_me, etc.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved', models.BooleanField(default=False, help_text='Set True once an admin has reviewed/reprocessed this message')),
            ],
            options={
                'verbose_name': 'Failed Message',
                'verbose_name_plural': 'Failed Messages',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at', 'resolved'], name='moderation__created_f6b3a3_idx')],
            },
        ),
    ]
