# Generated by Django 5.2.12 on 2026-06-05 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moderation', '0025_add_failed_message_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moderationresult',
            name='message_key_id',
            field=models.CharField(blank=True, db_index=True, help_text='Evolution API message key for deletion and deduplication', max_length=255, null=True),
        ),
    ]
