# Generated by Django 5.2.12 on 2026-06-08 15:41

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moderation', '0026_add_index_message_key_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='securityalert',
            name='calls_made',
            field=models.PositiveIntegerField(default=0, help_text='Number of Twilio voice calls made to parent for this alert'),
        ),
        migrations.AddField(
            model_name='securityalert',
            name='sms_sent',
            field=models.PositiveIntegerField(default=0, help_text='Number of Twilio SMS messages sent to parent for this alert'),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('alert', models.ForeignKey(help_text='The underlying SecurityAlert', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='moderation.securityalert')),
                ('user', models.ForeignKey(help_text='The user who sees this notification in their inbox', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='moderation__user_id_9a10c0_idx'), models.Index(fields=['user', 'is_read'], name='moderation__user_id_634713_idx')],
            },
        ),
    ]
