# Generated by Django 5.2.12 on 2026-06-17 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moderation', '0028_add_is_voice_message_to_moderation_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='feedback',
            field=models.CharField(choices=[('none', 'No feedback'), ('up', 'Thumbs up'), ('down', 'Thumbs down')], default='none', help_text='User feedback on this message: up (helpful), down (not helpful), none', max_length=4),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='feedback_comment',
            field=models.TextField(blank=True, default='', help_text='Optional user comment explaining their feedback'),
        ),
    ]
