# Generated by Django 5.2.12 on 2026-06-17 20:12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moderation', '0029_add_chatbot_message_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='is_proactive',
            field=models.BooleanField(default=False, help_text='True if this message was generated by the proactive alert system'),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='is_proactive',
            field=models.BooleanField(default=False, help_text='True if this session was created by the proactive alert system'),
        ),
        migrations.CreateModel(
            name='ProactiveAlert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('trigger_count', models.PositiveIntegerField(help_text='Number of flagged messages that triggered this alert')),
                ('trigger_window_hours', models.PositiveIntegerField(default=24, help_text='Rolling window (in hours) used to count flagged messages')),
                ('alert_categories', models.JSONField(default=list, help_text='List of primary_class categories involved in this alert')),
                ('is_acknowledged', models.BooleanField(default=False, help_text='True if the parent has acknowledged/dismissed this alert')),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('chat_message', models.ForeignKey(help_text='The assistant message generated as the proactive alert', on_delete=django.db.models.deletion.CASCADE, related_name='proactive_alert', to='moderation.chatmessage')),
                ('chat_session', models.ForeignKey(help_text='The chatbot session created for this proactive alert', on_delete=django.db.models.deletion.CASCADE, related_name='proactive_alerts', to='moderation.chatsession')),
                ('parent', models.ForeignKey(help_text='The parent user who received this proactive alert', on_delete=django.db.models.deletion.CASCADE, related_name='proactive_alerts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Proactive Alert',
                'verbose_name_plural': 'Proactive Alerts',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['parent', '-created_at'], name='moderation__parent__08dd00_idx'), models.Index(fields=['parent', 'is_acknowledged'], name='moderation__parent__191aef_idx')],
            },
        ),
    ]
