# Generated by Django 5.2.12 on 2026-06-17 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moderation', '0030_add_proactive_alert_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatsession',
            name='language',
            field=models.CharField(default='fr', help_text='Session language: fr, ar, en, darija', max_length=10),
        ),
    ]
