"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.12.
"""

import os
import logging
from pathlib import Path
from dotenv import load_dotenv

# Load variables from .env file into the environment
load_dotenv()

BASE_DIR = Path(__file__).resolve().parent.parent

# Security settings
SECRET_KEY = os.getenv('SECRET_KEY')
if not SECRET_KEY:
    raise ValueError("FATAL: SECRET_KEY environment variable is not set. Add it to your .env file.")
DEBUG = os.getenv('DEBUG', 'True') == 'True'
ALLOWED_HOSTS = os.getenv('ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',')

# Application definition
INSTALLED_APPS = [
    'daphne',                          # MUST be first! (Replaces normal dev server with Async server)
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',                  # For our API endpoints
    'rest_framework_simplejwt',        # For JWT authentication
    'corsheaders',                     # Allows Angular to talk to Django
    'channels',                        # Enables WebSockets
    'moderation',                      # Our custom app (we will build this next)
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',  # MUST be first
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'
ASGI_APPLICATION = 'config.asgi.application'  # Tells Django to use ASGI (Channels) instead of WSGI

# Database config pointing to your PostgreSQL instance
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.getenv('DB_NAME'),
        'USER': os.getenv('DB_USER'),
        'PASSWORD': os.getenv('DB_PASSWORD'),
        'HOST': os.getenv('DB_HOST'),
        'PORT': os.getenv('DB_PORT'),
    }
}

# Redis config for WebSockets
CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels_redis.core.RedisChannelLayer',
        'CONFIG': {
            "hosts": [os.getenv('REDIS_URL', 'redis://127.0.0.1:6379/1')],
        },
    },
}

# ── Cache Configuration ──────────────────────────────────────────────
# Redis DB 2 for Django's cache framework.
# DB 0 = prediction cache (prediction_cache.py), DB 1 = Channels/WebSockets
# Django 5.2 has built-in RedisCache — no extra package needed.
# We force DB 2 regardless of REDIS_URL's DB number to avoid collisions.
_redis_base = os.getenv('REDIS_URL', 'redis://127.0.0.1:6379')
# Strip any trailing /N to ensure we connect to DB 2
_redis_host = _redis_base.rsplit('/', 1)[0] if _redis_base.count('/') >= 3 else _redis_base
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.redis.RedisCache',
        'LOCATION': f'{_redis_host}/2',
        'KEY_PREFIX': 'aegis',
        'TIMEOUT': 300,  # Default 5 min TTL
    }
}

# CORS — restrict to known frontend origins
CORS_ALLOWED_ORIGINS = os.getenv(
    'CORS_ALLOWED_ORIGINS',
    'http://localhost:4200,http://127.0.0.1:4200'
).split(',')

# ML Pipeline Configuration loaded from .env
M1_MODEL_PATH = os.getenv('M1_MODEL_PATH')
M2_MODEL_PATH = os.getenv('M2_MODEL_PATH')
M1D_MODEL_PATH = os.getenv('M1D_MODEL_PATH', 'ml_pipeline/trained_models/M1D_darijabert')
M1_THRESHOLD = float(os.getenv('M1_THRESHOLD', 0.48))
M1D_THRESHOLD = float(os.getenv('M1D_THRESHOLD', 0.48))
AEGIS_STUB_MODE = os.getenv('AEGIS_STUB_MODE') == 'True'


# ── Colored Terminal Logging ─────────────────────────────────────────
# Makes ML predictions, Agent 3 reasoning, tool calls, and verdicts visible
# in the terminal with color-coded output.
class _ColorFormatter(logging.Formatter):
    """ANSI color formatter for terminal output."""
    COLORS = {
        'DEBUG':    '\033[36m',   # cyan
        'INFO':     '\033[32m',   # green
        'WARNING':  '\033[33m',   # yellow
        'ERROR':    '\033[31m',   # red
        'CRITICAL': '\033[41m',   # red background
    }
    RESET = '\033[0m'
    BOLD  = '\033[1m'
    DIM   = '\033[2m'

    def format(self, record):
        color = self.COLORS.get(record.levelname, self.RESET)
        # Color the level name
        record.levelname = f"{color}{self.BOLD}{record.levelname:<8}{self.RESET}"
        # Dim the logger name
        record.name = f"{self.DIM}{record.name}{self.RESET}"
        return super().format(record)


LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'colored': {
            '()': _ColorFormatter,
            'format': '%(levelname)s %(name)s │ %(message)s',
        },
        'plain': {
            'format': '%(levelname)-8s %(name)s │ %(message)s',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'colored',
            'stream': 'ext://sys.stdout',
        },
    },
    'loggers': {
        # ML pipeline — model predictions, routing, Agent 3 reasoning
        'ml_pipeline': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
        # Moderation app — webhook processing, cache, enforcer
        'moderation': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'WARNING',  # Only show WARNING+ from other libraries
    },
}

# Password validation & Internationalization (defaults)
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]

LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'Africa/Casablanca'
USE_I18N = True
USE_TZ = True
STATIC_URL = 'static/'
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Custom user model (UML Package 1 — must be set before first migration)
AUTH_USER_MODEL = 'moderation.AegisUser'

# JWT Authentication config
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ],
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.UserRateThrottle',
    ],
    'DEFAULT_THROTTLE_RATES': {
        'user': '120/min',         # General API: 120 requests/min per user
        'chatbot': '15/min',       # Chatbot ask endpoint: 15 requests/min (protects Groq TPM)
        'knowledge_upload': '10/min',  # Knowledge uploads: 10/min
    },
}

from datetime import timedelta

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(days=1),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'SIGNING_KEY': SECRET_KEY,
    'AUTH_HEADER_TYPES': ('Bearer',),
    'UPDATE_LAST_LOGIN': True,
}
