import uuid
from django.db import models
from django.utils import timezone

from .users import AegisUser
from .moderation import ModerationResult


# ╔══════════════════════════════════════════════════════════════╗
# ║  UML PACKAGE 5 — ALERTS & NOTIFICATIONS                    ║
# ║  SecurityAlert (enhanced) + Notification (per-user inbox)   ║
# ╚══════════════════════════════════════════════════════════════╝

class SecurityAlert(models.Model):
    """
    UML Package 5: Alerte
    Notification object generated by the moderation pipeline.
    Enhanced with UML fields: notification channel, resolution, recipient.
    """
    class AlertType(models.TextChoices):
        PUSH = 'push', 'Push Notification'
        EMAIL = 'email', 'Email'
        SMS = 'sms', 'SMS'
        CALL = 'call', 'Phone Call'

    class Severity(models.TextChoices):
        LOW = 'low', 'Low'
        MEDIUM = 'medium', 'Medium'
        HIGH = 'high', 'High'
        CRITICAL = 'critical', 'Critical'

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    moderation_result = models.ForeignKey(ModerationResult, on_delete=models.CASCADE, related_name='alerts')

    # UML-aligned fields
    alert_type = models.CharField(max_length=10, choices=AlertType.choices, default=AlertType.PUSH,
        help_text="Notification delivery channel")
    severity = models.CharField(max_length=20, choices=Severity.choices, default=Severity.MEDIUM)
    message_preview = models.CharField(max_length=255)

    # Recipient — who this alert is for
    recipient = models.ForeignKey(AegisUser, on_delete=models.CASCADE,
        null=True, blank=True, related_name='received_alerts',
        help_text="User who should receive this alert (parent or admin)")

    # State
    is_read = models.BooleanField(default=False)
    is_resolved = models.BooleanField(default=False)
    parent_notified = models.BooleanField(default=False,
        help_text="External notification (SMS/email/call) was sent to parent")

    # Delivery tracking — counts Twilio actions taken for this alert
    calls_made = models.PositiveIntegerField(default=0,
        help_text="Number of Twilio voice calls made to parent for this alert")
    sms_sent = models.PositiveIntegerField(default=0,
        help_text="Number of Twilio SMS messages sent to parent for this alert")

    sent_at = models.DateTimeField(auto_now_add=True)
    resolved_at = models.DateTimeField(null=True, blank=True)

    class Meta:
        verbose_name = "Security Alert"
        ordering = ['-sent_at']

    def __str__(self):
        return f"ALERT {self.severity} - {self.sent_at.strftime('%Y-%m-%d %H:%M')}"

    def mark_as_read(self):
        self.is_read = True
        self.save(update_fields=['is_read'])

    def resolve(self):
        self.is_resolved = True
        self.resolved_at = timezone.now()
        self.save(update_fields=['is_resolved', 'resolved_at'])


class Notification(models.Model):
    """
    Per-user notification inbox entry.
    Links a SecurityAlert to a specific user (admin or parent) with read tracking.
    One SecurityAlert can fan out to multiple Notification records (one per admin + parent).
    """
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    user = models.ForeignKey(AegisUser, on_delete=models.CASCADE, related_name='notifications',
        help_text="The user who sees this notification in their inbox")
    alert = models.ForeignKey(SecurityAlert, on_delete=models.CASCADE, related_name='notifications',
        help_text="The underlying SecurityAlert")
    is_read = models.BooleanField(default=False, db_index=True)
    read_at = models.DateTimeField(null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True, db_index=True)

    class Meta:
        verbose_name = "Notification"
        ordering = ['-created_at']
        indexes = [
            models.Index(fields=['user', '-created_at']),
            models.Index(fields=['user', 'is_read']),
        ]

    def __str__(self):
        return f"Notif({self.user.username}) — {self.alert.severity} — {'read' if self.is_read else 'unread'}"

    def mark_as_read(self):
        if not self.is_read:
            self.is_read = True
            self.read_at = timezone.now()
            self.save(update_fields=['is_read', 'read_at'])
